---
cloud_controller_discovery_interval: 300
cloud_controller_uri: http://api.10.244.0.34.xip.io
component_connection_retries: 2
cloud_controller_ssl_verify_none: true
data_file: data/data.json
log_file: admin_ui.log
log_file_page_size: 51200
log_file_sftp_keys: ["/home/idcuser/bluemixngkp.pem"]
log_files:
- admin_ui.log
- "sftp://vcap@10.0.116.16/var/vcap/sys/log/**/*.log"
- "sftp://vcap@10.0.116.29/var/vcap/sys/log/**/*.log"
- "sftp://vcap@10.0.116.15/var/vcap/sys/log/**/*.log"
mbus: nats://nats:nats@10.244.0.6:4222
monitored_components: [NATS, CloudController, DEA, HealthManager, Router, -Provisioner, ALL]
nats_discovery_interval: 30
nats_discovery_timeout: 10
port: 8070
receiver_emails: [ ]
sender_email:
  server: us.ibm.com
  account: CloudOE-admin@webconf.ibm.com
stats_file: data/stats.json
stats_refresh_time: 300
stats_retries: 5
stats_retry_interval: 300
tasks_refresh_interval: 5000
uaa_admin_credentials:
  username: admin
  password: admin
ui_credentials:
  username: IBMadmin
  password: IBM0331password
ui_admin_credentials:
  username: admin
  password: IBMpassw0rd
varz_discovery_interval: 30

